# Generated by Django 4.2.2 on 2023-08-27 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KuProApp', '0003_alter_ad_seller_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default='078333283', max_length=25),
        ),
    ]
